### ISSUE TITLE
No Access to Demo possible`?

### ISSUE THREAD

**Issue by agilisgmbh** [shinesoftware/shineisp2#13]
Hi Guys,
is this Project still in active developement?
Want to login into your Demo, but there are no login information on the demosite.
Can you provide something?

regards from Austria, Marco

**Comment by shinesoftware** [comment]
hi @agilisgmbh yes it is still alive. 
Look at: https://github.com/shinesoftware/shineisp2/wiki#administration-site

**Comment by agilisgmbh** [comment]
Maybe I´m to "dumb" for this, but i cant see anything when i´m logged in.
No configurations, nothing...
Please see attached Screen


mit winterlichen Grüßen aus Leobersdorf
Marco Hagen, Director Marketing & Sales
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
agilis GmbH - Gesellschaft für neue Medien
Wittmannsdorfer Hof 2 Top 6, A-2544 Leobersdorf
Tel: +43 (0)2256 / 93 038 Fax: DW 90

gesendet online via Hosted Exchange<http://www.hosted-exchange.co.at>
________________________________
Von: Michelangelo Turillo [notifications@github.com]
Gesendet: Freitag, 09. Jänner 2015 11:46
An: shinesoftware/shineisp2
Cc: agilis GmbH
Betreff: Re: [shineisp2] No Access to Demo possible`? (#13)


hi @agilisgmbh<https://github.com/agilisgmbh> yes it is still alive.
Look at: https://github.com/shinesoftware/shineisp2/wiki#administration-site

**Comment by shinesoftware** [comment]
Which screenshot are you talking about?

**Comment by agilisgmbh** [comment]
oh, i answered via EMail Acocunt and attached the screen when Im logged in.
Sry.
So, when I´m logged in i cant see anything. No options for settings, products, invoices, etc.
Nothing. Just edit my password, change email and log out.
nothing else

**Comment by shinesoftware** [comment]
Please follow as described in the documentation, the steps:

    Then you have to go at http://demo2.shineisp.com/admin

Remember I am starting from a scratch and there are many things to do. If you are a developer fork the project and start to create new modules.

At the moment there is the thin skeleton of the new version.

Regards
