### ISSUE TITLE
No navigation available

### ISSUE THREAD

**Issue by HHMichaelLo** [shinesoftware/shineisp2#15]
Moin moin,
in my fresh installed shineisp2 project i have no working navigation... see the screenshot
https://www.dropbox.com/s/vr2j2qvmegs43fo/Screenshot%202015-06-15%2003.11.15.png?dl=0
the same i have in your demo site

All images in the navigation are broken and all links dosnt work... the same in the frontend...
Greetings Michael

**Comment by shinesoftware** [comment]
Hi @HHMichaelLo,

what do you mean with: "all links don't work"? Which is the error message?

regards

**Comment by HHMichaelLo** [comment]
Hi, 
this is my start page: https://www.dropbox.com/s/6h77ac2kbrinrqz/Screenshot%202015-06-15%2016.18.35.png?dl=0
You can see that all images in the navigation are broken...
- The home link works but give me a 404 error
- Data lines give me a Oops, our fault! site
- Contact us works
- Admin works only the image bevor are broken
- My profile dosn't work - the only change is the url www.myurl.com/# but the drop down is not working the same by the languages

in the Admin Area all links not working without any message. all Links show me www.myurl.com//admin#
all drop downs are not working so i have only the Admin start page

-

**Comment by shinesoftware** [comment]
Hi,
the start page has been not found because you have to create a page by the CMS module with a slug "homepage". 

Which are the broken images in the administration section, the icons?
What do you mean with: "My profile don't work?"

Admin links don't work... which is the error message?

PS: Attach the screenshot to this page using a drag and drop.

**Comment by HHMichaelLo** [comment]
but the cms link in the admin area show me only www.myurl.com/admin# the dropdown are not oben to create a page with the slug "homepage". 

yes i mean the icons... frontend and backend i have no icons 
![screenshot 2015-06-15 03 11 15](https://cloud.githubusercontent.com/assets/1254365/8162743/8fbb4dac-137f-11e5-8b27-1fda5a17e8a9.png)

![screenshot 2015-06-15 16 18 35](https://cloud.githubusercontent.com/assets/1254365/8162751/a129d66c-137f-11e5-9986-9c70bb03e4a0.png)

and i become no error messages... nothing is changed... i see only the admin start page...

**Comment by HHMichaelLo** [comment]
After a fresh installation everything is working... 
![screenshot 2015-06-16 02 13 06](https://cloud.githubusercontent.com/assets/1254365/8173403/363a1bd4-13cd-11e5-9b01-965986467a66.png)

But if I change something, for example the name in: www.myurl.com/admin/base i have the same... no working navigation...

If I truncate the base_settings DB everything is working again...???

**Comment by shinesoftware** [comment]
Really strange. I am checking it.

**Comment by HHMichaelLo** [comment]
Hi, 
after your last commit i remove all files on my server and upload your latest version. 
But i cant install shineisp2... Please look at: www.isphamburg.com

**Comment by shinesoftware** [comment]
I can see your installation correctly. 
![schermata 2015-06-21 alle 10 25 20](https://cloud.githubusercontent.com/assets/1553035/8270992/dd00ba50-17ff-11e5-8596-3e559671384b.jpg)
