### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by aditaa** [shinesoftware/shineisp2#18]
Have tried installing with centos 6 & 7 and ubuntu 14.04
Running 'sudo php composer.phar update' reports errors :

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for cderue/googlemaps dev-master -> satisfiable by cderue/googlemaps[dev-master].
    - Conclusion: don't install zendframework/zendframework 2.3.9
    - Conclusion: don't install zendframework/zendframework 2.3.8
    - Conclusion: don't install zendframework/zendframework 2.3.7
    - Conclusion: don't install zendframework/zendframework 2.3.6
    - Conclusion: don't install zendframework/zendframework 2.3.5
    - Conclusion: don't install zendframework/zendframework 2.3.4
    - Conclusion: don't install zendframework/zendframework 2.3.3
    - Installation request for thadafinser/zfc-datagrid dev-master -> satisfiable by thadafinser/zfc-datagrid[dev-master].
    - Conclusion: don't install zendframework/zendframework 2.3.2
    - thadafinser/zfc-datagrid dev-master requires zendframework/zend-paginator ~2.5 -> satisfiable by zendframework/zend-paginator[2.5.0, 2.5.1].
    - don't install zendframework/zend-paginator 2.5.0|don't install zendframework/zendframework 2.3.0
    - don't install zendframework/zend-paginator 2.5.1|don't install zendframework/zendframework 2.3.0
    - cderue/googlemaps dev-master requires zendframework/zendframework 2.\* -> satisfiable by zendframework/zendframework[2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.3.9].
    - Conclusion: don't install zendframework/zendframework 2.3.1

**Comment by aditaa** [comment]
In the wiki it says :

Now execute this command by SSH:

php composer.phar self-update
php composer.phar update
Wait the end of the process.

But you have to run "php composer.phar install"

Wiki should be updated

**Comment by shinesoftware** [comment]
hi it is updated ... look at: https://github.com/shinesoftware/shineisp2/wiki/Download

where do you see that text?

regards
