### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by benji-lewis** [shinesoftware/shineisp2#20]
There is a typo in the description as it is displaying as "Don't be hesitate". I don't know if this is due to my device or if it is a typo.

**Comment by shinesoftware** [comment]
Can you explain what do you want to achieve?

**Comment by benji-lewis** [comment]
In the description of the project it says "Don't be hesitate ... contact us!" I do not understand this.

**Comment by shinesoftware** [comment]
this sentence means that we are open to collaborations with other developers.

**Comment by benji-lewis** [comment]
It would sound better if it said "Don't hesitate to contact us" as it makes more sense.

**Comment by shinesoftware** [comment]
thanks
