### ISSUE TITLE
Demo login not working

### ISSUE THREAD

**Issue by mylselgan** [shinesoftware/shineisp2#22]
The following details not working

http://demo2.shineisp.com/user/login
User: demo@shineisp.com
Pass: 1234567890

Authentication failed. Please try again.

**Comment by shinesoftware** [comment]
Please use the following information:

http://demo2.shineisp.com/user/login
User: demo@shineisp.com
Pass: 123456789

regards

**Comment by mylselgan** [comment]
Thanks for the login. it works now, but no link at the admin page is working. Please check
